swipe left to open menu on phone
alyrow/cyrel pull request #5
Opened 2021-12-22 19:38 UTC by hcaumeil

2021-12-22 21:56 UTC, alyrow requested changes

2021-12-22 21:56 UTC, alyrow commented on web/public/js/ui/top-bar.js
> +            };
Can be move outside the forEach at line 12

2021-12-22 21:56 UTC, alyrow commented on web/public/js/ui/top-bar.js
> +                var yDiff = yDown - yUp;
Usage of `let` is better

2021-12-22 21:56 UTC, alyrow commented on web/public/js/ui/top-bar.js
> +            };
Move functions before `document.addEventListner` and transform them in expression (I find that more clear in this context) like this:

```js
const hello = function(name) {
   console.log("Hello " + name);
}
```

2021-12-25 17:42 UTC, hcaumeil commented
Changes have been done

2021-12-26 09:23 UTC, alyrow approved these changes

2021-12-26 09:24 UTC, merged